version: '2'
services:
    portal-app:
        image: portal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://portal-mysql:3306/portal?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=portal-elasticsearch:9300
        ports:
            - 8080:8080
    portal-mysql:
        extends:
            file: mysql.yml
            service: portal-mysql
    portal-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: portal-elasticsearch
